# Generated by Django 6.0.5 on 2026-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
